### ISSUE TITLE
instantiating SemanticSettings is causing a build error

### ISSUE THREAD

**Issue by kenche0820** [Azure-Samples/azure-search-dotnet-samples#146] opened 2023-12-22 16:58 UTC
The following line of code is causing a build error:

SemanticSettings semanticSettings = new SemanticSettings();  

This came from [Quickstart: semantic ranking - Azure AI Search | Microsoft Learn](https://learn.microsoft.com/en-us/azure/search/search-get-started-semantic?tabs=dotnet)

I was able to follow the tutorial but when I copied the code into my web app it would not compile.  Any idea why?  I’ve attached the file I’m editing as well as the build log file.  Thanks in advance for your help.

Kenneth
[0_Build and Deploy Job.txt](https://github.com/Azure-Samples/azure-search-dotnet-samples/files/13754386/0_Build.and.Deploy.Job.txt)
[Search.cs.txt](https://github.com/Azure-Samples/azure-search-dotnet-samples/files/13754392/Search.cs.txt)

**Comment by HeidiSteen** [comment] 2024-01-02 19:34
Hi @kenche0820, the issue is now fixed.  The sample is updated to use the latest stable version and the SemanticConfiguration class.  Doc update will be published later today.  Thanks for reporting the bug.

**Closed by HeidiSteen** 2024-01-02 19:34 UTC
